### ISSUE TITLE
UK IP incorrectly identified as from IN

### ISSUE THREAD

**Issue by ekmpspete** [ip2location/ip2location-activex#1]
The following methods all incorrectly indendify the UK IP address "84.66.231.47" as from India (IN).

* `CCountry::LookUpShortName`
* `CCountry::LookUpLongName`
* `CCountry::LookUpFullName`

It looks like these methods all use `CCountry::GetCodeByIPAddress` [link](https://github.com/ip2location/ip2location-activex/blob/fae4542fce90d21ff1ebed73dd279417d08bd904/IP2LocationActiveX/Country.cpp#L258) which in depends on data in `ipcountry` [link](https://github.com/ip2location/ip2location-activex/blob/fae4542fce90d21ff1ebed73dd279417d08bd904/IP2LocationActiveX/IPData.h). Probably just a case of updating this array with up to date IP ranges.

**Comment by ip2location-com** [comment]
Those methods have been deprecated. Please use the LookUp method along with a BIN file instead.

See the sample codes at https://github.com/ip2location/ip2location-activex/tree/master/SampleCodes
